--- #YAML:1.0
name:               PDL-Graphics-Gnuplot
version:            0.01
abstract:           Gnuplot-based plotter for PDL
author:
    - Dima Kogan <dima@secretsauce.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IPC::Run:    0
    PDL:         0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
